### ISSUE TITLE
torch.nn.modules.module.moduleattributeerror: 'modelbuilder' object has no attribute 'crm'

### ISSUE THREAD

**Issue by Wang123z** [xyl-507/CRM#1]
作者你好，代码中modelbuilder好像没有crm这个属性

**Comment by Wang123z** [comment]
这个错误来源于CRM/CRM-Siam/tools里面的train.py的第99行trainable_params += [{'params': model.crm.parameters(), 'lr': cfg.TRAIN.BASE_LR}]

**Comment by xyl-507** [comment]
不好意思，最近在出差，无法修改代码。原因应该在于module_builder.p中的crm叫mvt，所以只需要把train.py中的crm换成mvt即可，等我回去会重新修改一下。
感谢您的关注！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月12日 17:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [xyl-507/CRM] torch.nn.modules.module.moduleattributeerror: 'modelbuilder' object has no attribute 'crm' (Issue #1) |

这个错误来源于CRM/CRM-Siam/tools里面的train.py的第99行trainable_params += [{'params': model.crm.parameters(), 'lr': cfg.TRAIN.BASE_LR}]

**Comment by Wang123z** [comment]
作者你好，又发现了两个问题

第一个问题：我训练好了CRM-Siam，我想测试一下UAV123数据集，但是您提供的命令中
START=10
END=20
seq $START 1 $END | \
    xargs -I {} echo "snapshot/checkpoint_e{}.pth" | \
    xargs -I {} \ 
    python -u ../../tools/test.py \
        --snapshot {} \
    --config config.yaml \
    --dataset UAV20L 2>&1 | tee logs/test_dataset.log
这里的test.py是没有的，只有test-multi.py，请问可以上传一下吗？
    
第二个问题：siamban/tracker/siamban_tracker.py第351行'counting': self.counting2,SiamBANTracker没有counting2这个属性

**Comment by xyl-507** [comment]
@Wang123z 
感谢你的反馈，我已经更正上述问题。
第一个问题的命令，应该是（我在README.md中说过，TRAIN.md的还未来得及修改，不好意思）
python -u ../../tools/test-multi.py --snapshot CRM-Siam.pth --config config-CRM-Siam.yaml --dataset MDOT
第二个问题：
self.counting2是我实现过程中的参数，代码已经更新了。
