### ISSUE TITLE
The attribute analysis plot based on the MDOT dataset

### ISSUE THREAD

**Issue by Jasper0420** [xyl-507/CRM#2]
![image](https://github.com/xyl-507/CRM/assets/63343279/aed23277-fb99-45ce-ac32-b23afe19d921)
Thank you for your contribution to tracking community engagement!
I'm going to FOLLOW your work and measure it on the Mdot dataset, and I was wondering how you drew your attribute analysis plot based on the MDOT dataset? Can you provide the raw_tracking for those methods in the graph. i did not find them! Thanks!
Good luck!

**Comment by xyl-507** [comment]
@Jasper0420 
Thanks for your attention.
These tracker results are what I got from testing with the official code, and I have uploaded the raw result (.TXT files) for some of the trackers in https://github.com/xyl-507/CRM/releases/tag/Raw_Results

**Comment by Jasper0420** [comment]
That's great!
Thank you for what you've done!
