### ISSUE TITLE
跑Demo示例时出错

### ISSUE THREAD

**Issue by wagh311** [xyl-507/CRM#4]
您好，我在运行Demo时，出现了以下报错：
Traceback (most recent call last):
  File "tools/demo.py", line 137, in <module>
    main()
  File "tools/demo.py", line 112, in main
    outputs = tracker.track(frame)
TypeError: track() missing 2 required positional arguments: 'idx' and 'v_idx'
请问这个是为什么啊？

**Comment by xyl-507** [comment]
现有的demo.py针对的是单无人机，如果有需要可以参照test-multi.py自行改动。

**Comment by wagh311** [comment]
好的，谢谢解答！
