### ISSUE TITLE
在个人数据集上使用CRM-DiMP

### ISSUE THREAD

**Issue by Hunan-Tiger** [xyl-507/CRM#6]
您好，非常感谢您的这项工作，我想将CRM-DiMP在个人数据集上使用得到bbox，
命令如下：python run_video.py dimp dimp50 /home/ljm/projects/CRM-DiMP/video/video.mp4，
但是遇到了以下error：
RuntimeError: Error(s) in loading state_dict for DiMPnet:
        Missing key(s) in state_dict: "mvt.conv2.weight", "mvt.conv2.bias", "mvt.conv3.weight", "mvt.conv3.bias", "mvt.bra.lepe.weight", "mvt.bra.lepe.bias", "mvt.bra.qkv_linear.weight", "mvt.bra.qkv_linear.bias", "mvt.bra.output_linear.weight", "mvt.bra.output_linear.bias". 
       期待您的回复！

**Comment by xyl-507** [comment]
可以参考readme，我们使用的是super-dimp，而不是dimp50

**Comment by Hunan-Tiger** [comment]
好的，非常感谢！
