### ISSUE TITLE
关于got10k数据集的预处理问题

### ISSUE THREAD

**Issue by wagh311** [xyl-507/CRM#7]
您好，我按照got10k数据集中的parse_got10k.py生成got10k.json，但发现生成的got10k.json非常的大，有100多G，想请问下这是正常的吗？因为在读取这个got10k.json时，服务器会崩掉，后续的train.json和val.json也无法生成

**Comment by xyl-507** [comment]
不会的，json文件不会这么大。实在不行，可以使用CRM-DiMP，不需要生成训练集的json文件

**Comment by wagh311** [comment]
> 不会的，json文件不会这么大。实在不行，可以使用CRM-DiMP，不需要生成训练集的json文件

我查看了got10k中的parse_got10k.py代码，发现它在用循环读取got10k数据集的9000多个文件夹，运行了好久，下面是输出的一些信息。请问您是否有got10k生成好的train.json和val.json，可以方便发一下吗？
![image](https://github.com/user-attachments/assets/079a655d-d74a-4e83-ad99-0afb1916bd4c)

**Comment by xyl-507** [comment]
已上传，百度云链接: https://pan.baidu.com/s/1979OoDtWfPfqrNoaqeApOg?pwd=qei9 提取码: qei9

**Comment by wagh311** [comment]
非常感谢！
