### ISSUE TITLE
关于最优训练结果的挑选

### ISSUE THREAD

**Issue by wagh311** [xyl-507/CRM#8]
大佬你好，不好意思又打扰您了，我想请教一下：
在算法训练过程中我应该如何去验证模型的效果呢？假如算法训练了20个epoch，每个epoch都有一个pth结果，那么我应该如何从中选择最优的结果呢？我看您的代码使用了pysot框架，但pysot似乎没有在训练过程中去验证模型效果的这部分代码，所以想请教一下您是如何解决这个问题的？

**Comment by xyl-507** [comment]
每个都测试一下就知道哪个是最好的了，我一般测试后五个。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月25日 15:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [xyl-507/CRM] 关于最优训练结果的挑选 (Issue #8) |

大佬你好，不好意思又打扰您了，我想请教一下：
在算法训练过程中我应该如何去验证模型的效果呢？假如算法训练了20个epoch，每个epoch都有一个pth结果，那么我应该如何从中选择最优的结果呢？我看您的代码使用了pysot框架，但pysot似乎没有在训练过程中去验证模型效果的这部分代码，所以想请教一下您是如何解决这个问题的？

**Comment by wagh311** [comment]
请问您是用最后5个直接在测试集上去验证吗？如果我验证自己的一些idea，是只要训练几个epoch就测试，还是要训练比较多epoch(比如20个)然后再挑选最后5个来验证啊？您一般采用哪种方式啊？

**Comment by xyl-507** [comment]
最后一种



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月25日 21:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xyl-507/CRM] 关于最优训练结果的挑选 (Issue #8) |

请问您是用最后5个直接在测试集上去验证吗？如果我验证自己的一些idea，是只要训练几个epoch就测试，还是要训练比较多epoch(比如20个)然后再挑选最后5个来验证啊？您一般采用哪种方式啊？

**Comment by wagh311** [comment]
好的，谢谢！
